In [1]:
### Data Manipulation with numpy and pandas

import pandas as pd

In [2]:
df=pd.read_csv('dataset.csv')
## fetch the first 5 rows
df.head(5)

      Trip_ID    start_area       end_area distance_km   time_of_day
0  TRIP_00001       Kalkaji           9.44       Night       Weekday
1  TRIP_00002       Kalkaji           2.15       Night       Weekend
2  TRIP_00003     Janakpuri     Model Town       14.54  Morning Peak
3  TRIP_00004  Punjabi Bagh          11.86       Night       Weekday
4  TRIP_00005        Rohini  Chandni Chowk       20.26     Afternoon

In [3]:
df.tail(5)

       Trip_ID       start_area   end_area distance_km   time_of_day
37  TRIP_01291      IGI Airport      AIIMS       10.81     Afternoon
38  TRIP_01292           Dwarka      Okhla       23.01  Morning Peak
39  TRIP_01293        Janakpuri  Hauz Khas       13.61         Night
40  TRIP_01294  Noida Sector 18  Janakpuri       23.96         Night
41  TRIP_01295  Noida Sector 18  Pitampura       24.06  Evening Peak

In [13]:
df.describe()

           Trip_ID start_area end_area   distance_km   time_of_day
count           42         42       42            42            35
unique          42         20       28            33             7
top     TRIP_00001    Kalkaji    Okhla  Evening Peak  Evening Peak
freq             1          3        4             5            10

In [4]:
df.dtypes

Trip_ID        object
start_area     object
end_area       object
distance_km    object
time_of_day    object
dtype: object

In [5]:
## Renaming columns
df=df.rename(columns={'Trip_ID':'Id_trip'})
df.head()

      Id_trip    start_area       end_area distance_km   time_of_day
0  TRIP_00001       Kalkaji           9.44       Night       Weekday
1  TRIP_00002       Kalkaji           2.15       Night       Weekend
2  TRIP_00003     Janakpuri     Model Town       14.54  Morning Peak
3  TRIP_00004  Punjabi Bagh          11.86       Night       Weekday
4  TRIP_00005        Rohini  Chandni Chowk       20.26     Afternoon

In [15]:
## Handling missing values
df.isnull().any()

Trip_ID        False
start_area     False
end_area       False
distance_km    False
time_of_day     True
dtype: bool

In [16]:
df.isnull().sum()

Trip_ID        0
start_area     0
end_area       0
distance_km    0
time_of_day    7
dtype: int64

In [ ]:
##